### PR TITLE
prophet 1.1.4: Rebuild for py38

### PR DESCRIPTION
**Pull request by skupr-anaconda**
Missing artifacts for py38

See https://github.com/facebook/prophet/blob/c9301685466b5dc8d0c94eef03c791c1c0db3856/python/pyproject.toml#L14

### CODE REVIEW

**Review by M-Waszkiewicz-Anaconda — COMMENTED** [review]
bump up build number ?

**Comment by skupr-anaconda** [comment]
> bump up build number ?

I'm building only py38 artifacts so it's fine to not bump the build number

**Review by M-Waszkiewicz-Anaconda — APPROVED** [review]
LGTM

**Comment by JeanChristopheMorinPerso** [comment]
>>bump up build number ?
>
>I'm building only py38 artifacts so it's fine to not bump the build number

It's fine only because the dependencies in the host section are baked. And even that is still risky because the compiler could have changed, `{{ numpy }}` coming from aggregate could also have changed, etc. If this happens, then you have an artifact that will differ (either only a little or significantly) from the other artifacts for the same version+build number.

In general, not bumping the build number isn't safe in our current ecosystem (for packages that require a compilation step).

**Pull request merged**
